# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: AYAMIM.AwaCut
PackageVersion: 1.0.4
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
  - Architecture: x64
    InstallerUrl: https://dl.awacut.com/releases/1.0.4/AwaCut_1.0.4_x64-setup.exe
    InstallerSha256: 0E9CE5F0129336942484002CE45E44F5E55FB13AFEC24C62751DB8F8DA5433F4
ManifestType: installer
ManifestVersion: 1.10.0
