# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: AYAMIM.AwaCut
PackageVersion: 1.0.5
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
  - Architecture: x64
    InstallerUrl: https://dl.awacut.com/releases/1.0.5/AwaCut_1.0.5_x64-setup.exe
    InstallerSha256: A32AEF3F373AB77B69DAD3408B36EA62699913B5A6BADE2136B6D0D225CF4737
ManifestType: installer
ManifestVersion: 1.12.0
